
#DB設定 H2を使用
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8
    initialize: true
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true